name: Terraform Deploy Workflow
on:
  workflow_dispatch:  # Permite ejecución manual desde GitHub Actions

jobs:
  deploy:
    name: Deploy Infrastructure with Terraform
    runs-on: ubuntu-latest
    steps:
      # Paso 1: Checkout del código fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Configurar Terraform CLI
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.4

      # Paso 3: Configurar las credenciales de AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Paso 4: Crear el bucket S3 (si no existe) y configurar permisos de borrado
      - name: Create S3 Bucket for Terraform State
        run: |
          BUCKET_NAME="pin-grupo-4"

          # Verificar si el bucket ya existe
          if ! aws s3api head-bucket --bucket $BUCKET_NAME 2>/dev/null; then
            # Crear el bucket
            aws s3api create-bucket \
              --bucket $BUCKET_NAME \
              --region us-east-1

            # Habilitar el versionado
            aws s3api put-bucket-versioning \
              --bucket $BUCKET_NAME \
              --versioning-configuration Status=Enabled

            # Habilitar el cifrado en el bucket
            aws s3api put-bucket-encryption \
              --bucket $BUCKET_NAME \
              --server-side-encryption-configuration '{"Rules": [{"ApplyServerSideEncryptionByDefault": {"SSEAlgorithm": "AES256"}}]}'

            # Configurar una política de bucket que permita la eliminación
            POLICY='{
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Principal": "*",
                  "Action": [
                    "s3:DeleteObject",
                    "s3:DeleteObjectVersion",
                    "s3:DeleteBucket"
                  ],
                  "Resource": [
                    "arn:aws:s3:::'$BUCKET_NAME'",
                    "arn:aws:s3:::'$BUCKET_NAME'/*"
                  ]
                }
              ]
            }'
            echo "Configurando política de bucket para permitir la eliminación..."
            aws s3api put-bucket-policy \
              --bucket $BUCKET_NAME \
              --policy "$POLICY"
          else
            echo "El bucket ya existe. No es necesario crearlo."
          fi

      # Paso 5: Inicializar Terraform (esto configurará el backend S3)
      - name: Initialize Terraform
        run: terraform init

      # Paso 6: Ejecutar Terraform Plan y guardar el plan en un archivo
      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      # Paso 7: Ejecutar Terraform Apply solo cuando el plan sea exitoso y en la rama main
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve